export enum ErrorCodes {
  DOMAIN_ERROR = 'DOMAIN_ERROR',
  DOMAIN_INVALID_EMAIL_ERROR = 'INVALID_EMAIL_ERROR',
  DOMAIN_INVALID_ID_ERROR = 'INVALID_ID_ERROR',
  DOMAIN_ENTITY_NOT_FOUND_ERROR = 'ENTITY_NOT_FOUND_ERROR',
  DOMAIN_ENTITY_VALIDATION_ERROR = 'ENTITY_VALIDATION_ERROR',
  DOMAIN_PASSWORD_INVALID_ERROR = 'PASSWORD_INVALID_ERROR',
  DOMAIN_TODO_ITEM_INVALID_ERROR = 'TODO_ITEM_INVALID_ERROR',
  DOMAIN_TODO_INVALID_ERROR = 'TODO_INVALID_ERROR',
  DOMAIN_TODO_NOT_FOUND_ERROR = 'TODO_NOT_FOUND_ERROR',
  APPLICATION_ERROR = 'APPLICATION_ERROR',
  INFRASTRUCTURE_ERROR = 'INFRASTRUCTURE_ERROR',
  BASE_ERROR = 'BASE_ERROR',
};
